services:
  frankenphp:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    container_name: frankenphp
    ports:
      - "8080:8080"
    volumes:
      - ./web:/app
    command: sh -c '[ -f /app/.env ] || cp /app/.env.example /app/.env && frankenphp run --config /etc/caddy/Caddyfile'
    depends_on:
      - clickhouse

  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123" # HTTP port
      - "9000:9000" # Native port
    environment:
      - CLICKHOUSE_DB=events_bench
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=strongpassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/migrations:/docker-entrypoint-initdb.d

volumes:
  clickhouse_data:
