// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#ifndef _CLICKHOUSEPHP_H
#define _CLICKHOUSEPHP_H

#include <php.h>
#include <stdint.h>

extern zend_module_entry clickhousephp_module_entry;

// Thread-local last-error channel (defined in clickhousephp.c). Set from Go,
// read by the PHP-function bridge — see the comment in clickhousephp.c.
void ch_set_last_error(const char *msg, long code);
long ch_last_error_code(void);
const char *ch_take_last_error(void);

#endif
